from datetime import date,timedelta
import json
from sqlalchemy import select
from sqlalchemy.orm import Session
from .db import HealthCondition,KnowledgeEntry,KnowledgeSource,Meal
CONDITIONS=[("Diabetes","diabetes","Educational meal-planning information."),("High blood pressure","high-blood-pressure","Heart-healthy eating education."),("High cholesterol","high-cholesterol","Heart-healthy food-pattern education."),("Anemia","anemia","Education that supports cause-aware care."),("PCOS","pcos","Balanced, individualized lifestyle education.")]
SOURCES={"diabetes":("Centers for Disease Control and Prevention","Diabetes Meal Planning","https://www.cdc.gov/diabetes/healthy-eating/diabetes-meal-planning.html"),"high-blood-pressure":("National Heart, Lung, and Blood Institute","DASH Eating Plan","https://www.nhlbi.nih.gov/education/dash-eating-plan"),"high-cholesterol":("American Heart Association","Prevention and Treatment of High Cholesterol","https://www.heart.org/en/health-topics/cholesterol/prevention-and-treatment-of-high-cholesterol"),"anemia":("National Heart, Lung, and Blood Institute","Anemia","https://www.nhlbi.nih.gov/health/anemia"),"pcos":("Office on Women's Health","Polycystic Ovary Syndrome","https://womenshealth.gov/a-z-topics/polycystic-ovary-syndrome")}
GENERAL_SOURCES={"nutrition":("National Institute of Diabetes and Digestive and Kidney Diseases","Healthy Eating and Physical Activity","https://www.niddk.nih.gov/health-information/weight-management/healthy-eating-physical-activity-for-life"),"hydration":("Centers for Disease Control and Prevention","Water and Healthier Drinks","https://www.cdc.gov/healthyschools/features/water-access.html"),"activity":("World Health Organization","Physical activity","https://www.who.int/news-room/fact-sheets/detail/physical-activity"),"sleep":("Centers for Disease Control and Prevention","About Sleep and Your Health","https://www.cdc.gov/sleep/about/index.html")}
GENERAL_TOPICS=[
 ("fiber","Dietary fibre is the part of plant foods that the body does not fully digest.","nutrition"),("fiber","Foods such as beans, lentils, fruits, vegetables and whole grains can provide dietary fibre.","nutrition"),("protein","Protein is a nutrient found in foods including beans, lentils, eggs, dairy, fish, meat, soy foods, nuts and seeds.","nutrition"),("carbohydrates","Carbohydrates are nutrients found in foods such as grains, fruit, beans and dairy foods.","nutrition"),("healthy_fats","Unsaturated fats from foods such as nuts, seeds and plant oils can fit into a balanced eating pattern.","nutrition"),("whole_grains","Whole grains contain the bran, germ and endosperm of the grain.","nutrition"),("whole_grains","Examples of whole grains include oats, brown rice and whole-wheat foods.","nutrition"),("vegetables","Vegetables contribute variety and nutrients to eating patterns.","nutrition"),("fruits","Fruits can be part of a varied eating pattern.","nutrition"),("legumes","Beans, peas and lentils are legumes and can be used in many meals.","nutrition"),("nuts_seeds","Nuts and seeds can be included in meals and snacks when they suit a person's preferences and needs.","nutrition"),("hydration","Hydration means having enough fluids for the body to function normally.","hydration"),("hydration","Water is a practical drink choice for hydration for many people.","hydration"),("balanced_meals","A balanced meal can include a mix of foods such as vegetables, protein foods and carbohydrate-containing foods.","nutrition"),("portion_awareness","Portion awareness means noticing how much food is served or eaten, without judging foods or bodies.","nutrition"),("added_sugars","Food labels can help people identify added sugars in packaged foods and drinks.","nutrition"),("sodium","Sodium is a nutrient listed on Nutrition Facts labels.","nutrition"),("food_labels","Nutrition labels can help people compare packaged food products.","nutrition"),("minimally_processed","Minimally processed foods can be practical options within a varied eating pattern.","nutrition"),("dietary_variety","Dietary variety can help make meals more interesting and practical.","nutrition"),("physical_activity","Physical activity includes movement that uses energy and can be adapted to ability and circumstance.","activity"),("sleep","Sleep is an important part of overall health and daily routines.","sleep"),("stress_management","Stress-management approaches can be individualized and may include supportive routines or professional support.","sleep")]
TOPICS={
"diabetes":[("meal_planning","Meal planning can help organize food choices as part of an overall eating pattern."),("carbohydrates","Carbohydrate-containing foods can be considered as part of balanced meals."),("vegetables","Non-starchy vegetables can add color and variety to meals."),("whole_grains","Whole grains can be included in a balanced eating pattern."),("fiber","Fiber-containing foods can be part of a varied meal pattern."),("added_sugars","Food-label awareness can help identify added sugars."),("minimally_processed","Minimally processed foods can be useful options when practical."),("food_labels","Reading food labels can support informed food choices."),("consistent_eating","A consistent eating routine may be helpful to discuss with a care team."),("balanced_meals","Balanced meals can reflect preferences, culture, and schedule.")],
"high-blood-pressure":[("dash","A DASH-style eating pattern emphasizes fruits, vegetables, whole grains, beans, nuts, seeds, and low-fat dairy foods."),("sodium","Sodium awareness is one part of a heart-healthy eating pattern."),("vegetables","Vegetables can be included in a DASH-style eating pattern."),("fruits","Fruits can be included in a DASH-style eating pattern."),("whole_grains","Whole grains are included in DASH-style eating patterns."),("legumes","Beans and legumes can be part of heart-healthy meals."),("nuts_seeds","Nuts and seeds can be included in heart-healthy eating patterns."),("processed_foods","Comparing labels can help identify sodium in highly processed foods."),("food_labels","Food labels provide information that can support informed choices."),("heart_healthy","Heart-healthy patterns are best adapted with a qualified professional when needed.")],
"high-cholesterol":[("fiber","Fiber-containing foods can be part of heart-healthy eating patterns."),("whole_grains","Whole grains can add fiber and variety to meals."),("fruits","Fruits can be part of a heart-healthy pattern."),("vegetables","Vegetables can be part of a heart-healthy pattern."),("unsaturated_fats","Unsaturated fats, including those from plant foods, can fit in heart-healthy patterns."),("fat_quality","Replacing some saturated-fat sources with unsaturated-fat sources can support a heart-healthy pattern."),("processed_foods","Minimally processed food choices can be useful when practical."),("food_labels","Food labels can help people compare food products."),("heart_healthy","Heart-healthy dietary patterns are general education, not medication advice."),("balanced_meals","Meals can be balanced around preferred foods and practical access.")],
"anemia":[("medical_evaluation","Anemia has different causes, so identifying the cause is important for appropriate care."),("causes","Not every case of anemia is caused by iron deficiency."),("iron_foods","Iron-containing foods can be part of a varied eating pattern."),("food_sources","Beans, lentils, meat, seafood, and iron-fortified foods are examples of foods that can contain iron."),("vitamin_c","Vitamin C has a role in dietary iron absorption context, but individual guidance can differ."),("professional_care","A healthcare professional can help evaluate symptoms and identify the cause."),("balanced_meals","Food choices are supportive education and do not replace evaluation."),("supplements","Do not begin iron supplements or change doses based only on general education."),("individualized","Dietary needs differ with the cause of anemia and a person's health context."),("safety","Seek timely professional care for concerning symptoms or questions about treatment.")],
"pcos":[("balanced_pattern","People with PCOS can discuss a balanced, sustainable eating pattern with a qualified professional."),("individualized_care","Food choices for PCOS should account for preferences, needs, and healthcare guidance."),("sustainable","Sustainable changes can respect culture, access, schedule, and preferences."),("balanced_meals","Balanced meals can be a practical starting point for general wellness."),("lifestyle","General lifestyle care can be individualized with a healthcare professional."),("no_cure_claims","No single diet should be presented as a cure for PCOS."),("avoid_restriction","Avoid extreme restriction and appearance-based or weight-shaming language."),("meal_planning","Meal planning can help make preferred food routines practical."),("food_preferences","Personal preferences are important when building a sustainable routine."),("professional_care","Professional guidance can help tailor care to personal needs.")]}
MEALS=[("Vegetable oats upma","breakfast","Indian","vegetarian",20,["oats","mixed vegetables","peas","lemon"],"fiber,whole-grain"),("Berry yogurt oats","breakfast","Mediterranean","vegetarian",10,["oats","yogurt","berries","chia seeds"],"fiber"),("Savory vegetable poha","breakfast","Indian","vegan",20,["poha","peas","carrots","lemon"],"quick,fiber"),("Chickpea salad plate","lunch","Mediterranean","vegetarian",15,["chickpeas","tomatoes","cucumber","lemon"],"fiber"),("Lemon lentil rice bowl","lunch","Indian","vegetarian",25,["lentils","brown rice","cucumber","tomatoes"],"fiber"),("Vegetable quinoa bowl","lunch","Global","vegan",25,["quinoa","broccoli","chickpeas","lemon"],"fiber"),("Roasted vegetable dal","dinner","Indian","vegetarian",35,["red lentils","spinach","carrots","brown rice"],"fiber"),("Herbed bean soup","dinner","Mediterranean","vegan",30,["white beans","tomatoes","spinach","herbs"],"fiber"),("Tofu vegetable stir-fry","dinner","Asian","vegan",30,["tofu","broccoli","bell pepper","brown rice"],"quick"),("Apple and nut butter","snack","Global","vegetarian",5,["apple","peanut butter"],"quick"),("Hummus vegetable cup","snack","Mediterranean","vegan",10,["hummus","carrots","cucumber"],"quick"),("Pear and walnuts","snack","Global","vegan",5,["pear","walnuts"],"quick")]
def seed_database(db:Session):
 conditions={c.slug:c for c in db.scalars(select(HealthCondition)).all()}
 for name,slug,desc in CONDITIONS:
  if slug not in conditions: conditions[slug]=HealthCondition(name=name,slug=slug,description=desc); db.add(conditions[slug])
 db.flush()
 sources={s.title:s for s in db.scalars(select(KnowledgeSource)).all()}
 for slug,(org,title,url) in SOURCES.items():
  if title not in sources: sources[title]=KnowledgeSource(organization=org,title=title,url=url,last_checked=date.today(),description="Official health guidance."); db.add(sources[title])
 db.flush()
 for slug,items in TOPICS.items():
  existing={e.topic for e in db.scalars(select(KnowledgeEntry).join(KnowledgeEntry.conditions).where(HealthCondition.slug==slug)).all()}
  for topic,claim in items:
   if topic not in existing:
    e=KnowledgeEntry(source_id=sources[SOURCES[slug][1]].id,claim=claim,explanation=claim+" This is general educational information, not a diagnosis or treatment plan.",topic=topic,evidence_level="official_guidance",population_scope="General educational context.",applicability="Use for general educational personalization only.",limitations="Individual needs and medical care may differ.",review_status="approved",reviewed_by="clinical-review-demo",reviewed_at=date.today(),next_review_at=date.today()+timedelta(days=180)); e.conditions.append(conditions[slug]); db.add(e)
 for key,(org,title,url) in GENERAL_SOURCES.items():
  if title not in sources: sources[title]=KnowledgeSource(organization=org,title=title,url=url,last_checked=date.today(),description="Official general health guidance."); db.add(sources[title])
 db.flush()
 existing_general={e.claim for e in db.scalars(select(KnowledgeEntry).where(~KnowledgeEntry.conditions.any())).all()}
 for topic,claim,source_key in GENERAL_TOPICS:
  if claim not in existing_general:
   db.add(KnowledgeEntry(source_id=sources[GENERAL_SOURCES[source_key][1]].id,claim=claim,explanation=claim+" This is general educational information and not personal medical advice.",topic=topic,evidence_level="official_guidance",population_scope="General wellness education.",applicability="Use for general educational explanations.",limitations="Personal needs and medical care may differ.",review_status="approved",reviewed_by="clinical-review-demo",reviewed_at=date.today(),next_review_at=date.today()+timedelta(days=180)))
 existing_meals={m.name:m for m in db.scalars(select(Meal)).all()}
 for name,typ,cuisine,diet,mins,ingredients,tags in MEALS:
  meal=existing_meals.get(name)
  values={"description":"A practical meal idea built around everyday ingredients.","meal_type":typ,"cuisine":cuisine,"diet_type":diet,"preparation_time":mins,"tags":tags,"ingredients":json.dumps(ingredients),"compatible_conditions":"diabetes,high-blood-pressure,high-cholesterol,anemia,pcos","instructions":"Prepare ingredients, cook as appropriate, and season to taste."}
  if meal:
   for key,value in values.items(): setattr(meal,key,value)
  else: db.add(Meal(name=name,**values))
 db.commit()
